### ISSUE TITLE
Date is shown as the chosen format instead of real date

### ISSUE THREAD

**Issue by ErikvanD** [bhavesh-jadav/Advance-Card#10]
When I drag a single date field into the visual it is shown as **dddd %d MMMM yyyy** instead of a real date value like **Thursday 9 August 2018**. When I try the same column in the standard single row or multi row card visuals it does show the actual date value

**Comment by ErikvanD** [comment]
Super! I'll just have some patience then. Thx!

**Comment by bhavesh-jadav** [comment]
Fixed in v1.0.8
