### ISSUE TITLE
Text Pushed Out of Card When Using Category Label in Internet Explorer

### ISSUE THREAD

**Issue by cahilfoley** [bhavesh-jadav/Advance-Card#14]
**Describe the bug**
When viewing the cards through the Power BI web application in Internet Explorer the text appears to be pushed out of the top of the box.

**To Reproduce**
1. Add an Advanced Card visualisation to a report
2. Add a category label to the card
3. Publish the report to the Power BI service
4. View the report in Internet Explorer

**Expected behavior**
The text should appear in the middle of the card as it does in most browsers (see screenshots below).

**Screenshots**
Behaviour in Chrome (expected)
![chrome](https://user-images.githubusercontent.com/14274957/44713275-6562b300-aae5-11e8-9772-b44d1e26af91.jpg)

Behaviour in IE
![internet-explorer](https://user-images.githubusercontent.com/14274957/44713287-6eec1b00-aae5-11e8-848f-8b3bd6da6777.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Internet Explorer
 - Version 11.0.80

**Additional context**
IE's dev tools don't like me inspecting Power BI applications but from what I could load the problem looked like the issue was around [this line](https://github.com/bhavesh-jadav/Advance-Card/blob/ae1a063821b852343ae17706d8e9076357f9b9c5/src/visual.ts#L368). From what I could see of the error message was `TypeError: Object doesn't support property or method 'getBBox'`.

Removing the category label allows the card to behave normally.

**Comment by bhavesh-jadav** [comment]
@cahilfoley Thank you for detailed information.

Apparently `getBBox` method was not working in IE so I replaced it with `getBoundingClientRect` and that is working in IE. I have updated the visual and will be available in Power BI soon.

**Comment by cahilfoley** [comment]
That was fast! Thanks for fixing that up.

I've just checked and can confirm that it's all working as expecting in IE now 👍

**Comment by Planda** [comment]
Hi @bhavesh-jadav,

the problem still persist for me. I am using the visual on Power BI Report Server (August 2018), but even after update the category label is messing with the visual.

I am using IE 11.1209.15063.0. Do I need to update something on server side?

Thank you

**Comment by bhavesh-jadav** [comment]
This fix is available in version 1.1.2. Current available version on Power BI is v1.1.1. I have added version 1.1.2 on AppSource but it will take some time to available on Power BI.
