### ISSUE TITLE
Visual Not Loading in Firefox

### ISSUE THREAD

**Issue by nima1i** [bhavesh-jadav/Advance-Card#15]
**Describe the bug**
When a report, containing this visual, is published to the Power BI service and the service is opened with Firefox, the visual is not loaded completely. Also when the report is published to the web and the published link is opened with Firefox, the visual is not loaded completely.

**To Reproduce**
1. Insert this visual to a report
2. Publish the report to Power BI service
3. Open Power BI service with Firefox
4. Open Report in the service
5. See error

**Expected behavior**
The visual is expected to load completely is Firefox.

**Screenshots**
Link to sample Report: http://bit.ly/2CpjquB
On Chrome:
![image](https://user-images.githubusercontent.com/43040549/45167915-67c4bb80-b20f-11e8-873d-674ca8cd4b6c.png)

On Firefox:
![image](https://user-images.githubusercontent.com/43040549/45167985-8aef6b00-b20f-11e8-9666-cf52debfb6ab.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 
 - Version  v 62.0

**Additional context**
----

**Comment by bhavesh-jadav** [comment]
Hi @nima1i 

I have fixed this issue in v1.1.2 and it is updated on AppSource but it will take some time for it to become available on Power BI.

**Comment by nima1i** [comment]
Thanks, I will close the issue as soon as the fix is available on Power BI.
