### ISSUE TITLE
Is there any way to show conditional formatting using another column itself in the data?

### ISSUE THREAD

**Issue by harkrish1** [bhavesh-jadav/Advance-Card#18]
Eg. I want to show current year plan cost in comparison with last year plan cost.

**Comment by bhavesh-jadav** [comment]
If you want to compare current year plan cost with last year plan cost, then create measure with following logic(e.g.).
If current year plan cost > last year plan cost then return 1 else return 0.
Put this new measure in Condition field and set condition for values 1 and 0.

**Comment by harkrish1** [comment]
That’s great. Thanks!
