### ISSUE TITLE
Color Selector not working

### ISSUE THREAD

**Issue by kilicantplay** [bhavesh-jadav/Advance-Card#19]
Hi, 

Currently the colour selector is not working when trying to set any elements with the config in Power BI.  

Power BI version: 2.62.5222.761
Advance card version: 1.1.3.0

I found the below on the forum which appears to link the issue to a change in the API by Microsoft.

https://community.powerbi.com/t5/Issues/Power-BI-Custom-Visual-Color-selector-giving-a-different-color/idc-p/540335#M33517

Kind Regards

Rob

**Comment by bhavesh-jadav** [comment]
Hi @kilicantplay 

Thank you for your feedback.
I was aware that theme color does not apply correctly to custom visual but I was not aware that they fixed that in API v2.1. Thank you for linking post confirming that using API v2.1 will fix this issue.
I will test Advance Card with API v2.1 and next version of Advance Card will be based on API v2.1 or later.

**Comment by kilicantplay** [comment]
Look forward to it :) thanks for the hard work, really appreciated

**Comment by bhavesh-jadav** [comment]
Hi @kilicantplay 

This is fixed in v2.0.1 of Advance Card which is available on Power BI.
