### ISSUE TITLE
Text Alignment

### ISSUE THREAD

**Issue by aruntd77** [bhavesh-jadav/Advance-Card#2]
Dear Bhavesh,

This visual is very nice and useful visual. It combines many features and thank you for coming up with this visual.

However I am requesting a feature to add for **Horizontal and Vertical Alignment for Data Label**.

I wanted to use Card Visual for P&L Report where in we report numbers (Currencies) and we would like to align the number to Right as finance standard.

Also if you can provide an option for **negative number - card to have option to format or show the numbers in round brackets.**

These two features will surely help for financial dashboard which all of the available card visuals lack.

**Comment by bhavesh-jadav** [comment]
@aruntd77 

1. For horizontal and vertical alignment can you post some screenshots about what kind of alignment are you talking about so that I can have a better idea.
2. Regarding showing negative number in brackets. you can achieve this through DAX. Using IF function and appending brackets to value if the number is negative.

**Comment by aruntd77** [comment]
![alignment issue](https://user-images.githubusercontent.com/19364755/41350103-0f29f4f6-6f23-11e8-89b5-447c98488189.png)
In the picture I have attached, I wanted to align the first text box number towards right. If you see, both boxes are having same width however no of digits are varying. Text is always center aligned. If we have any options to set the Horizontal Alignment in Settings, it will be of great help.

**Comment by bhavesh-jadav** [comment]
I will start working on this and will let you know on this thread. It may take some time. Thank you for your suggestion.

**Comment by aruntd77** [comment]
Thank you!

**Comment by aruntd77** [comment]
Hi Bhavesh,

Just wanted to give feedback on the visual. In my report, I had to use
around 70 cards to show the KPIs. When I did it using Advanced Card, the
data loading or showing the Visual is taking long time. I tested after
replacing all these cards with OOB cards then the report and Visual loading
is faster.

I also tried with Infogrpahic Visual, which again resulted in slow
performance while loading report.

There are no complex DAX queries.

I guess there is some issue while loading large no of custom visuals as
opposed to OOB visuals.

May be if you can do some load test, it might hint you to improve
performance.

Just wanted share my observation.

Thanks
Arun

**Comment by aruntd77** [comment]
Hi Bhavesh,

The default card is showing the cached data and then refreshes in less than
3 sec.

Advanced Card with 20 numbers on report takes 10-12 secs to load.

Single Advanced Card is taking about 2-3 secs to display data.

I am using Imported data, not direct query.

Thanks
Arun

**Comment by bhavesh-jadav** [comment]
Hi Arun,

Thank you for providing extra info. I will test the visual in different load test scenario with different browsers and see what it is that causing more time to load visual.

Thanks,
Bhavesh

**Comment by bhavesh-jadav** [comment]
Alignment feature is available in v1.0.6 of Advance card visual. You will find this setting in General properties. See wiki for more details. Download latest version from AppSource.
