### ISSUE TITLE
Power BI Certified

### ISSUE THREAD

**Issue by sickchic22** [bhavesh-jadav/Advance-Card#21]
**Is your feature request related to a problem? Please describe.**
I love this visual but need it to be a "certified" visual so it will export to PowerPoint and PDF (once its available)

**Describe the solution you'd like**
Complete the requirements to become a "certified" custom visual with Power BI

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bhavesh-jadav** [comment]
Advance Card is now Certified custom visual.

**Comment by sickchic22** [comment]
That’s fantastic!!


Amy Schneider
Consultant
Desk: +18472837429
Email: ASchneider@netrixllc.com
Service Center: +18774963698
www.netrixllc.com
This email and any     files transmitted with it are confidential and intended solely for the use     of the individual or entity to whom they are addressed. If you have     received this email in error please notify the system manager. This message     contains confidential information and is intended only for the individual     named. If you are not the named addressee you should not disseminate,     distribute or copy this e-mail.
