### ISSUE TITLE
Not posible to add more than 200 cards

### ISSUE THREAD

**Issue by thoenne** [bhavesh-jadav/Advance-Card#22]
Hello,
I want to create a heat map with more 400 cards. But Power BI crashes when I add more than 200 cards to the report. Is there a limitation? In addition the visual is very RAM consuming.
Thanks

Regards

**Comment by bhavesh-jadav** [comment]
Hi @thoenne 

Custom visual uses iframes to show data and iframes can be heavy on the browser. So for 400 cards it creates 400 iframes and I think that is why it is taking lot of RAM and crashing your browser.
I would not recommend that you use that many visuals in single page of the report. Even with Power BI's own visuals, it is bound to take more RAM and might crash.
You can also look at https://www.youtube.com/watch?v=1BHuy_vIyD0 for the heat map visual.

**Comment by thoenne** [comment]
Hi bhavesh-jadav,
I will check the video.

Thanks
