### ISSUE TITLE
Not showing up in IE11

### ISSUE THREAD

**Issue by laurajludwig** [bhavesh-jadav/Advance-Card#26]
**Describe the bug**
The card is empty when viewing a report on Internet Explorer 11 (version 11.407.17134.0). 

**To Reproduce**
1. View a report with this card in IE11
2. See error

**Expected behavior**
I expect the card to display correctly. 

**Screenshots**
Current view in IE11:
![image](https://user-images.githubusercontent.com/4369097/49307483-2ba99b80-f48a-11e8-97ed-b8cdeeccccbd.png)

Expected result, based on viewing in Chrome:
![image](https://user-images.githubusercontent.com/4369097/49307518-467c1000-f48a-11e8-9de2-8c11c303b22d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Internet Explorer
 - Version: IE version 11.407.17134.0

**Comment by pirasathl30** [comment]
Hello, 

I am experiencing the exact same issue as this also. 

Please keep me posted with any updated regarding this matter.

Many Thanks

Kind Regards

Piri

**Comment by eladioruiz** [comment]
Hello,
same problem for me.
More information: It works in Edge.

Many Thanks
Kind Regards

Eladio

**Comment by ghaughey** [comment]
I'm having this problem, too.  Was pulling my hair out.

**Comment by bhavesh-jadav** [comment]
I have fix this in v2.0.4 which is available on Appsource. But because of Power BI policy it takes 2 weeks for visual to get updated on Power BI after it gets approved on Appsource. 
I will send email to Power BI team and ask them to see if they can do any faster.
Apologies for inconvenience caused.

**Comment by ghaughey** [comment]
That's great to know, thanks. Will you comment here when it's available?

**Comment by bhavesh-jadav** [comment]
Yes, I will and you will be notified.

**Comment by vinaypm4u** [comment]
Hi Bhavesh. Have the same issue as well. Nice to see that you have a resolution in place. Please add me to the notification as well.

**Comment by jrgeorge40** [comment]
Downloaded the latest version from Appsource and it still doesn't show up in IE11.

**Comment by bhavesh-jadav** [comment]
Hi All,

IE issue is fixed in v2.0.4 and it is available on Power BI
