### ISSUE TITLE
Display Units: Percentage

### ISSUE THREAD

**Issue by JohnFlickinger** [bhavesh-jadav/Advance-Card#3]
I am interested in utilizing the Advance Card for a report I am building, however, don't seem to see an option to view the **Data Label as a percentage.** When I select auto, it defaults to thousands, rather than %.

Would love to see this feature implemented similarly to the default card as it is one of the greatest benefits for visualizing data.

**Comment by bhavesh-jadav** [comment]
Hi John,

Thank you for showing interest in Advance Card Visual. You will be able to see percentage format in advance card visual in next version. I will update this thread as soon as latest version is available on the appsource.

**Comment by marcosmota5** [comment]
Hello bhavesh-jadav,

This also includes another units? I mean, I have a data label where the number is formated with point separating the thousands (as it is used in my country), like this: "4.290". But the Advance Card Visual shows the number without the point, like this: "4290". Even with the number being formated in the right way.

Also, I want to thank you for this visual, it's one of the best I've ever seen.

**Comment by bhavesh-jadav** [comment]
Hi marcosmota5,

All the formatting issues will be fixed in next version i.e. probably by end of tomorrow. I will update this thread once it is available.

**Comment by Nexter1** [comment]
Hi @bhavesh-jadav ,

I was just wondering if this update might be out soon?  I really want to be able to use your card, but without adding in % and $ symbols, I just wouldn't be able to find a use for it.  Thanks!!

**Comment by bhavesh-jadav** [comment]
@Nexter1  It will be out by next week. I have already updated visual on AppSource a while ago but it takes additional two weeks to available on Power BI. See Note section in link below.
[https://docs.microsoft.com/en-us/power-bi/developer/office-store#submitting-to-power-bi](url)

**Comment by nickchobotar** [comment]
Hi bhavesh-jadav, 
In the formatting changes that we coming to the card, will there be possible to format data as currency ? 
Thanks

**Comment by bhavesh-jadav** [comment]
Hi nickchobotar,

Yes it will support all possible formatting.

**Comment by bhavesh-jadav** [comment]
Hi all,

The formatting issue is fixed in latest version i.e. v1.0.6 of Advance card. Download latest version from Appsource.
