### ISSUE TITLE
Advance card in PowerPoint not working

### ISSUE THREAD

**Issue by fernandocalero** [bhavesh-jadav/Advance-Card#31]
The advance card works well on Power BI service on Google Chrome, not on Internet Explorer, but when exporting to PowerPoint it does not show, only an "X" appears. I'm using December 2018 version.

Screenshot from PBI Service:

![pbi service](https://user-images.githubusercontent.com/3391678/50642956-5deb6480-0f32-11e9-9011-600040a98c85.png)

Screenshot from the exported PowerPoint file:

![pbi pp](https://user-images.githubusercontent.com/3391678/50643199-f97cd500-0f32-11e9-8db2-8ce4d4416bb1.png)

**Comment by wtanis** [comment]
Is there any update on this issue?

**Comment by fernandocalero** [comment]
Do I have to delete the current visualization and download it again? I'll do that tomorrow and let you know.
Thanks,
Fernando

**Comment by bhavesh-jadav** [comment]
Advance card is currently under certification process and once it is certified, it will export in PowerPoint. I'll update here once done.

**Comment by jrgeorge40** [comment]
Same for the Subscription?

--Josh

**Comment by bhavesh-jadav** [comment]
Yes

**Comment by bhavesh-jadav** [comment]
The Advance Card visual is now certified hence you will be able to export reports with Advance card in pdf and ppt.
