### ISSUE TITLE
Visual not exported upon Subscription

### ISSUE THREAD

**Issue by jrgeorge40** [bhavesh-jadav/Advance-Card#34]
**Describe the bug**
When subscribing to the report, there 

**To Reproduce**
1. Go to the Power BI report in the App
2. Subscribe to the report
3. View export

**Expected behavior**
I expect to see the export of the KPI.

**Screenshots**
![image](https://user-images.githubusercontent.com/9645044/52425762-44ee4a00-2ac2-11e9-930b-ad49c799435d.png)

**Comment by bhavesh-jadav** [comment]
Hi @jrgeorge40 

For custom visual to appear in email subscription it has to be certified. Certification for Advance card is under process and will update you here once it is certified.

**Comment by jrgeorge40** [comment]
Wonderful! Thanks!

**Comment by jonimatix** [comment]
Really interested in this as well!

**Comment by iTekExpert** [comment]
Can we have an estimate of how much time it could take for your visual to be certified?
Because I have to either wait for it, or redo my report with another visual before the go-live of my report.
Thank you!

**Comment by JBidw** [comment]
Any update on certification?  Export to PDF also not working ( assuming same error / same issue ) 

Thanks
--JB

**Comment by TMOCostanzo** [comment]
Not meaning to pile on, but we are looking to use this at our telecom company and it would be awesome to understand the progress so I know how much longer we need to export this as a manual process.
Beautiful product, and thank you so much for fixing an oversight on MS part.

**Comment by bhavesh-jadav** [comment]
The Advance Card visual is now certified hence you will be able to export reports with Advance card in pdf and ppt.
