### ISSUE TITLE
Card not displaying for non % metric in IE11

### ISSUE THREAD

**Issue by leeteikjian** [bhavesh-jadav/Advance-Card#36]
Describe the bug
The card is empty when viewing a report on Internet Explorer 11 (version 11.967.16299.0). Based on [previous issue closed](https://github.com/bhavesh-jadav/Advance-Card/issues/26), we tested using Advance Card 2.1.0. The component worked for percentage (%) measure, but when using numerical measure (decimal) it displays the same behavior shown in the [previous issue closed](https://github.com/bhavesh-jadav/Advance-Card/issues/26).

To Reproduce

View a report with this card in IE11
See error
Expected behavior
I expect the card to display correctly.

Screenshots
Current view in IE11:
![s1](https://user-images.githubusercontent.com/221032/53951491-defbdf00-40ce-11e9-81e4-7244bb2d4b36.PNG)

Expected result, based on viewing in Chrome:
![s2](https://user-images.githubusercontent.com/221032/53951495-e15e3900-40ce-11e9-902e-f09a25c52126.PNG)

Desktop (please complete the following information):

OS: Windows 10 Pro
Browser: Internet Explorer
Version: IE version 11.967.16299.0

**Comment by ghaughey** [comment]
I am also having this problem again on IE (it had been previously fixed)

**Comment by leeteikjian** [comment]
This issue is not reproducible on newer version of IE11 11.1029.16299.0. 
![image](https://user-images.githubusercontent.com/221032/55625713-d835ba00-57a9-11e9-97fe-f987b3c6c818.png)
