### ISSUE TITLE
Change background color without displaying value on the card

### ISSUE THREAD

**Issue by snama2020** [bhavesh-jadav/Advance-Card#4]
Hi Bhavesh, This is in respect to the query I asked via email. I followed your instruction but it looks like it just takes the background of first condition. In my case I have multiple conditions and based on the value, the background color should change.

For ex. 
If Risk%  < 0.05 Then Background Color = "Green"
If Risk% >= 0.05 AND Risk% < 0/29 Then Background Color = "Yellow"
IF Risk% >= 0.3 Then Background Color = "Red"

Thanks,
Srikanth

**Comment by bhavesh-jadav** [comment]
Hi Srikanth,

In version 1.0.0 of the card visual, there is bug with decimal number in conditional formatting where it takes first conditions even though it is not true. I have fixed the issue in latest version and waiting for it to appear it on Appsource. Regarding when will it appear on Appsource is depend on Microsoft. I will update this thread once it is available on Appsource.

Thanks,
Bhavesh

**Comment by snama2020** [comment]
I played with by changing the value to whole number but it wasn't working and then realized that the datatype for my field was decimal number. When I changed the data type to Whole number, it started working. Waiting for the latest version. 

Appreciate your prompt response.
