### ISSUE TITLE
Fails to Copy'n'Paste

### ISSUE THREAD

**Issue by aex-gh** [bhavesh-jadav/Advance-Card#43]
**Describe the bug**
Using Ctrl-C and Ctrl-P to cut'n'paste the visual fails to work.

**To Reproduce**
1. Create a visual using advance Card
2. Select the visual
3. Press Ctrl-C
4. Press Ctrl-V
5. It fails to paste a copy of the visual

**Expected behavior**
Expect a copy of the visual that was selected

Advanced Card version: 2.1.1
Power BI Version: 2.79.5768.1082 64-bit (March 2020)

**Comment by GigiLevens** [comment]
This works for me.
Advanced Card version: 2.1.1.0
Power BI Version: 2.87.684.0 64-bit (November 2020)

**Comment by kpuri245** [comment]
Copy and Paste do not work for me either. it's an absolute pain to have to create multiple individual cards. I'm using Macand chrome for the online service report creation.
