### ISSUE TITLE
Tooltip from textfield says "undefined"

### ISSUE THREAD

**Issue by svenvu** [bhavesh-jadav/Advance-Card#5]
Hi

It is not really a big issue but I want to let you know it anyway. 
When using a textfield for the advance card, the tooltip says "undefined" when you hoover over the text. For example:

![undefined](https://user-images.githubusercontent.com/41591565/43096178-8b75956a-8eb8-11e8-8fb2-45fb888e67f2.png)

This is only tested in power bi desktop. I am using advance card:
Version 1.0.7.0 Updated 5/20/2018

**Comment by bhavesh-jadav** [comment]
I can reproduce this bug. Fix will be available in next version. Thank you for notifying.

**Comment by bhavesh-jadav** [comment]
Fixed in v1.0.8
