### ISSUE TITLE
Advance Card not appearing on email subscriptions

### ISSUE THREAD

**Issue by shawshank1975** [bhavesh-jadav/Advance-Card#65]
**Describe the bug**
Since the July 2022 release, the advance cards have disappeared from the image in the email subscriptions on pinned pages.

**To Reproduce**
1. Pin an entire page to a dashboard. The advance cards appear fine:
![image](https://user-images.githubusercontent.com/109706069/180109694-dc69cc99-d985-4acc-95e9-682b51deb02b.png)
3. Run a subscription of the dashboard and send to yourself.
4. When the email is received, the advance cards will be missing. 
![image](https://user-images.githubusercontent.com/109706069/180109582-11e29726-7645-4fbb-b87d-694ed625a5c6.png)

**Expected behavior**
In step 4 above, the advance cards should appear

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by djmid78** [comment]
I have exactly the same issue. 
Do you have a solution ? 
For information, the problem appeared for the last week.

**Comment by shawshank1975** [comment]
My two cents - there isn't really a workaround so far - my only solution was to switch to the regular cards. Not ideal.
And agreed - the problem has appeared since the July 22 release.

**Comment by djmid78** [comment]
Thank you for your reply.

**Comment by shawshank1975** [comment]
Looks like this is resolved now.
