### ISSUE TITLE
Using a textfield in the tooltip

### ISSUE THREAD

**Issue by svenvu** [bhavesh-jadav/Advance-Card#7]
Hi

I would like to use a textfield as a tooltip but if I turn the tooltip on it says NaN.

![tooltip text](https://user-images.githubusercontent.com/41591565/43102081-6d5da010-8eca-11e8-9d3e-ae6a081abc7d.png)

I am using Power BI Desktop with advance card version 1.0.7.0 updated 5/20/2018
Is this something that could be fixed in a future version?

Friendly greets
Sven

**Comment by bhavesh-jadav** [comment]
Thank you for your feedback. I will look into this and update you with progress.

**Comment by bhavesh-jadav** [comment]
Fixed in v1.0.8

**Comment by svenvu** [comment]
This is great @bhavesh-jadav  :D looking forward to it!

Friendly greets
