### ISSUE TITLE
Not appearing when saved to server

### ISSUE THREAD

**Issue by ASharrock** [bhavesh-jadav/Advance-Card#8]
Hi,
We are using the Advance Card in our Power BI Desktop reports which look great, however when we save the report to our server, only some of the Advance cards appear.  

When accessing the report via our server, you can see the dots rotating to suggest that the visuals are there and working, but figures are only appearing for some of the visuals.  Loading the report outside the server, the visuals appear and work fine.

We are using Power BI Desktop March 2018.

Thank you

**Comment by ASharrock** [comment]
Hi,

Thank you for the quick response.

Yes, I am talking about Power BI Report Server.

I looked at the console browser and there are no errors.  Someone of the visuals work but not all, so I don’t think my company network is blocking resources.

Andrew

**Comment by bhavesh-jadav** [comment]
It difficult for me to debug this problem as I do not have access to Report Server. For sake of testing. 
**What happens when you publish report on online Power BI Service?**
**What type of data are you trying to show in card i.e. number, dates or text?**
Please let me know of answer to above questions.

**Comment by bhavesh-jadav** [comment]
@ASharrock is your issue resolved? I have updated the visual with various fixes. You can try the latest version and see if your problem goes away or not.

**Comment by ASharrock** [comment]
Sorry Bhavesh, I haven’t had time to look at this.

When I get a chance, I will download you’re your new visual to see if it works.  Thanks for taking a look and making the various fixes.

I have just closed the issue so it doesn’t show as open.

Thanks for your help

Andrew Sharrock
Senior Business Intelligence Developer
Business Intelligence Unit
Aintree House
Aintree Hospital
Longmoor Lane
Liverpool
L9 7AL
Tel: 0151 529 0549 ext 0549
E-mail: Andrew.Sharrock@aintree.nhs.uk<mailto:Andrew.Sharrock@aintree.nhs.uk>

**Comment by fernandocalero** [comment]
Hi Bhavesh,
I'm experiencing same problem while looking the report in Power BI Service in Internet Explorer browser, but in Chrome and in Power BI desktop it's ok.
My card is showing a % measure coloring the font red or green based on the target.
Regards,
Fernando

Here you can see what I do:

> Power BI Service from  Internet Explorer:
![advanced_card_ie](https://user-images.githubusercontent.com/3391678/49166878-d9d20b80-f2f9-11e8-9d25-9a282db4b6ac.png)

Power BI Service from Chrome:
![advanced_card_chrome](https://user-images.githubusercontent.com/3391678/49166886-dd659280-f2f9-11e8-9016-bbd58006dd93.png)
